### ISSUE TITLE
Do you support startTLS connections to LDAP?

### ISSUE THREAD

**Issue by tparkercbn** [Petlefeu/lbcssh#103]
Is it possible to use startTLS with LDAP authentication?  My LDAP server has an SSF of 256 and requires secure connections.

**Comment by nbeguier** [comment]
Does the v2.3.0 is responding to your need (put ldaps in the protocol) ?

**Comment by tparkercbn** [comment]
Let me try and I will let you know! 😊

Thank you

Tom

**Comment by tparkercbn** [comment]
Ldaps is not the same as starttls.   ldaps:// is deprecated in favor of Start TLS [RFC2830].

My Ldap servers do not support ldaps (but do support StartTLS)

Thank

**Comment by nbeguier** [comment]
Indeed, let me check the LDAP lib documentation

**Comment by nbeguier** [comment]
Hi again,
I finally managed to make my tests work on ldaps, so I will be able to support starttls very quickly.
Probably a PR tomorrow ;)

**Comment by nbeguier** [comment]
https://github.com/nbeguier/cassh/commit/5a69d7ea6e5dd4ed1e46ba343a8e67224be37357
Done

**Comment by tparkercbn** [comment]
Wow.  Awesome!  We will test it out tomorrow 😊

Thank you!
