### ISSUE TITLE
How to deploy CA files to ssh servers.

### ISSUE THREAD

**Issue by mattrose** [Petlefeu/lbcssh#80]
So, I have set up the cassh server, and created a key, but I have no idea how to deploy the files necessary to be able to use my newly created and signed key on an SSH server.

Could somebody write up some quick instructions on the following:

1.  What files are necessary to copy from either the CASSH server or the CASSH client to the remote SSH server?
2.  what sshd_config configuration options need to be set for the remote SSH server to be able to authenticate the CASSH-signed key.

**Comment by nbeguier** [comment]
You need to copy the public ca certificate on the remote ssh server. For example : `/etc/ssh/ca.pem`

Add this line in the `sshd_config`:
```
TrustedUserCAKeys /etc/ssh/CA.pem
```

Restart ssh server and it should works.

I'm available if you have other issues.
